spring.application.name=trainingslogger

spring.datasource.url=jdbc:postgresql://localhost:5433/trainingslogger
spring.datasource.username=postgres
spring.datasource.password=passwort

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true